 * pure Python
 * implement decision tree and regression tree with Gini index, max depth, min number of data points
 * comparison with sklearn
 * visualization of the decision path
 * analysis of hyperparameters impact in sklearn
 * linear trees

## Set up of data

We're taking the classic Titanic dataset

We did have to clean the data set by removing all unique columns

In [5]:
import numpy as np
import pandas as pd
import math
titanic = pd.read_csv('Titanic-Dataset.csv')

titanic.head()

# remove unique columns
titanic = titanic.drop(["PassengerId", "Name", "Cabin", "Ticket"], axis =1)

# change string columns to numbers
sex = {"female": 1, "male": 0}
embark = {"S": 0, "C": 1, "Q": -1}

titanic["Sex"] = titanic["Sex"].map(sex)
titanic["Embarked"] = titanic["Embarked"].map(embark)

# changing the name

data = titanic

data.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500       0.0
1         1       1    1  38.0      1      0  71.2833       1.0
2         1       3    1  26.0      0      0   7.9250       0.0
3         1       1    1  35.0      1      0  53.1000       0.0
4         0       3    0  35.0      0      0   8.0500       0.0

We will now set up the features vs the targets.

In [ ]:
features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]

data_feat = data[features]
data_tar = data["Survived"]

data_feat.head()

# split into training and testing 80/20?

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  22.0      1      0   7.2500       0.0
1       1    1  38.0      1      0  71.2833       1.0
2       3    1  26.0      0      0   7.9250       0.0
3       1    1  35.0      1      0  53.1000       0.0
4       3    0  35.0      0      0   8.0500       0.0

Dec tree

In [ ]:
# set up of nodes + info that would be on them
class Node:
    def __init__(self, gini, entropy, smth):
        self.gini = gini
        self.entropy = entropy
        self.smth = smth

# actual dec tree 
class Dec_tree:
    def __init__(self):
        pass

    def set_data():
        pass

## Gini index

$Gini=1−\sum_{i=1}^n ​p_i^2$

$Entropy=−\sum_{i=1}^n ​p_i\log_2(p_i)$

In [6]:
def gini(n, p):
    sum = 0
    i = 1
    for i in range(n):
        sum += p[i]**2
    
    return 1-sum

def entropy(n, p):
    sum = 0
    i = 1
    for i in range(n):
        sum += p[i]* math.log2(p[i])
    
    return -sum

Regression Tree