 * pure Python
 * implement decision tree and regression tree with Gini index, max depth, min number of data points
 * comparison with sklearn
 * visualization of the decision path
 * analysis of hyperparameters impact in sklearn
 * linear trees

## Set up of data

We're taking the classic Titanic dataset

We did have to clean the data set by removing all unique columns

In [5]:
import numpy as np
import pandas as pd
import math
titanic = pd.read_csv('Titanic-Dataset.csv')

titanic.head()

# remove unique columns
titanic = titanic.drop(["PassengerId", "Name", "Cabin", "Ticket"], axis =1)

# change string columns to numbers
sex = {"female": 1, "male": 0}
embark = {"S": 0, "C": 1, "Q": -1}

titanic["Sex"] = titanic["Sex"].map(sex)
titanic["Embarked"] = titanic["Embarked"].map(embark)

# changing the name

data = titanic

data.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500       0.0
1         1       1    1  38.0      1      0  71.2833       1.0
2         1       3    1  26.0      0      0   7.9250       0.0
3         1       1    1  35.0      1      0  53.1000       0.0
4         0       3    0  35.0      0      0   8.0500       0.0

We will now set up the features vs the targets.

In [ ]:
features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]

feature = data[features]
target = data["Survived"]

feature.head()

# split into training and testing 80/20?

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  22.0      1      0   7.2500       0.0
1       1    1  38.0      1      0  71.2833       1.0
2       3    1  26.0      0      0   7.9250       0.0
3       1    1  35.0      1      0  53.1000       0.0
4       3    0  35.0      0      0   8.0500       0.0

## Gini index

$Gini=1−\sum_{i=1}^n ​p_i^2$

$Entropy=−\sum_{i=1}^n ​p_i\log_2(p_i)$

![alt text](images/image.png)

In [ ]:
def gini(col):
    # calculate the unique elements and count them
    elements, count = np.unique(col, return_counts=True)
    # if catagorical values then there will be few unique elements

    gini = 0
    total = len(col)

    # if non catagorical
    if(count> total/4):
        pass
    
    for i in range(len(elements)):
        prob = count[i]/total
        gini += prob**2
    
    return 1-gini

def entropy(col):
    # calculate the unique elements and count them
    elements, count = np.unique(col, return_counts=True)

    entropy = 0
    total = len(col)

    for i in range(len(elements)):
        prob = count[i]/total
        entropy += prob * math.log2(prob)
    
    return - entropy

Dec tree

In [ ]:
def weighted_gini(col: str, target: str, data: np.ndarray):
    # col = name of columnn you might want to split on
    # target = the target: here "survied"
    # data = the entire data set

    survived = list()
    perished = list()

    for x in range(len(data[target])):
        if data[target][x] == 0:
            perished.append(data[col][x])
        else:
            survived.append(data[col][x])

    survived_weight = gini(np.array(survived)) * (len(survived)/len(data[target])) 
    perished_weight = gini(np.array(perished)) * (len(perished)/len(data[target]))

    return survived_weight+perished_weight

Regression Tree